config/routes.rb
Rails.application.routes.draw do

  resources :comments

  resources :contributions

  devise_for :users
  root 'welcome#index'
  resources :user

  resources :campaign do
    resources :contributions
    resources :comments
  end

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  validates :title, presence: true
  validates :target_amount, presence: true
  validates :country, presence: true
  validates :region, presence: true
  validates :city, presence: true
  validates :category, presence: true
  validates :image, presence: true
  validates :story, presence: true

  has_many :contributions
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :campaign
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :donation_amount, presence: true
  validates :email, presence: true
  validates :comment, presence: true

  belongs_to :campaign
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :contributions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    campaign_index_path
  end
end

app/controllers/campaign_controller.rb
class CampaignController < ApplicationController

  layout 'campaign'

  def index
  @campaigns = Campaign.all
  end

  def show
    @campaign= Campaign.find(params[:id])
    @comment = Comment.new
  end

  def new
  @campaign = Campaign.new
  end


  def campaigns_params
    params.require(:post).permit(:title, :target_amount, :country, :region, :city, :category, :image, :description, :story)
  end

  def create
    @campaign = Campaign.new(campaigns_params)

    if @campaign.save
      redirect_to campaign_path(@campaign), :notice => "Your campaign has been created!"
    else
      render "new"
    end
  end

  def edit
    @campaign= Campaign.find(params[:id])
  end

  def update
    @campaign= Campaign.find(params[:id])

    if @campaign.update_attributes(campaigns_params)
      redirect_to campaign_path, :notice => "Your campaign has been updated!"
    else
      render "edit"
    end
  end

  def destroy
    @campaign = Campaign.find(params[:id])
    @campaign.destroy
    redirect_to campaign_index_path, :notice => "Your campaign has been deleted"
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = Comment.all
  end

  def show
    @comment= Comment.find(params[:id])
    end

  def new
    @campaign = Campaign.find(params[:campaign_id])
    @comment = @campaign.comments.build
  end
  def edit
    @comment= Comment.find(params[:id])
  end

    def comment_params
      params.require(:comment).permit(:name, :text, :campaign_id)
    end

  def create
    @comment = Comment.new(comment_params)
    @comment.campaign_id=params[:campaign_id]

    if @comment.save
      redirect_to campaign_path(params[:campaign_id]), :notice => "Your contribution has been created!"
    else
      render "new"
    end
  end

  def update
    @comment= Comment.find(params[:id])

    if @comment.update_attributes(comment_params)
      redirect_to campaign_path(params[:campaign_id]), :notice => "Your comment has been updated!"
    else
      render "edit"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to comments_path, :notice => "Your comment has been deleted"
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :set_contribution, only: [:show, :edit, :update, :destroy]

  def index
    @contributions = Contribution.all

  end

  def show
    @contribution= Contribution.find(params[:id])
  end

  def new
    @campaign = Campaign.find(params[:campaign_id])
    @contribution = @campaign.contributions.build

  end

  def edit
    @contribution= Contribution.find(params[:id])
  end

  def contribution_params
    params.require(:contribution).permit(:first_name, :lastname, :email, :comment, :donation_amount, :campaign_id)
  end

  def create
    @contribution = Contribution.new(contribution_params)

    if @contribution.save

      redirect_to campaign_path(contribution_params[:campaign_id]), :notice => "Your contribution has been created!"
    else
      render "new"
    end
  end

  def update
    @contribution= Contribution.find(params[:id])

    if @contribution.update_attributes(contribution_params)
      redirect_to campaign_path(params[:campaign_id]), :notice => "Your campaign has been updated!"
    else
      render "edit"
    end
  end

  def destroy
    @contribution = Contribution.find(params[:id])
    @contribution.destroy
    redirect_to contributions_path, :notice => "Your contribution has been deleted"
  end

  private
  def set_contribution
    @contribution = Contribution.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :authenticate_user!
  layout "welcome"
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaign_helper.rb
module CampaignHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/campaign/edit.html.erb
<div class="container">
  <div class="grey" >
<h1>Editing campaign</h1>

<%= form_for @campaign, as: :post, url: campaign_path(@campaign), method: :patch  do |z| %>

    <div class="field">
      <%= z.label :Title %><br>
      <%= z.text_field :title %>
    </div>

    <div class="field">
      <%= z.label :Country %><br>
      <%= z.text_field :country %>
    </div>

    <div class="field">
      <%= z.label :Region %><br>
      <%= z.text_field :region %>
    </div>

    <div class="field">
      <%= z.label :City %><br>
      <%= z.text_field :city %>
    </div>

    <div class="field">
      <%= z.label :Category %><br>
      <%= z.text_field :category %>
    </div>

    <div class="field">
      <%= z.label :Share_your_Story %><br>
      <%= z.text_area :story %>
    </div>


    <div class="field">
      <%= z.label :Fundraising_Goal %><br>
      <%= z.text_field :target_amount %>
    </div>

    <p></p>

    <p>
      <%= z.file_field :image %>
    </p>
        </div>
        </div>
        <p></p>
    <p><%= z.submit 'Save Campaign Changes', :class => "btn btn-primary" %></p>
<% end %>

app/views/campaign/index.html.erb
<h1 style="text-align: center">These are the current Campaigns, Choose anyone to Help</h1>
<div class="greaty">
  <div class="row">
    <% @campaigns.each do |campaign| %>
        <div class="col-md-4">
          <div class="great">
            <div class="img">
              <%= link_to campaign.title, campaign %>
              <%= image_tag campaign.image_url(:thumb).to_s %>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>
<%= link_to 'Back', campaign_index_path, :class => "btn btn-primary" %>

app/views/campaign/new.html.erb
<div class="container" >
  <div class="alfred">
  <div class="grey" >
<h2>Welcome, Create a New Campaign</h2>

<%= form_for @campaign, as: :post, :html => {:multipart => true}, url: campaign_index_path(@campaign), method: :post do |z| %>

    <h2>Basic Details</h2>
    <div class="field">
    <%= z.label :Title %>
      <%= z.text_field :title %>
     </div>

    <div class="field">
      <%= z.label :Country %>
      <%= z.text_field :country %>
    </div>
    <p></p>
    <div class="field">
      <%= z.label :Region %>
      <%= z.text_field :region %>
    <!--</div>-->

    <!--<div class="field">-->
      <%= z.label :City %>
      <%= z.text_field :city %>
    </div>

   </div>
<!--</div>-->
<hr>
        <!--<div class="container">-->
          <div class="grey">
    <h2>Medical Details</h2>
            <div style="width: 300px">
    <label class="control-label">Category</label>
    <div class="controls">
      <p>
        <select name="post[category]" >
          <option value="Medical Expenses">Medical Expenses</option>
          <option value="Emergency Medical Expenses">Emergency Medical Expenses</option>
        </select>
      </p>
      </div>
    </div>

    <div class="field">
      <%= z.label :Fundraising_Goal %>
      <%= z.text_field :target_amount %>
    </div>

            <div class="field">
      <%= z.label :Add_an_Image %> <%= z.file_field :image %>
    </div>

    <div class="story">
    <%= z.label :Share_your_Story %>
      <%= z.text_area :story %>
      </div>

    <!--<p>-->
      <!--<%= z.label :remote_image_url, "or image URL" %>-->
      <!--<%= z.text_field :remote_image_url %>-->
    <!--</p>-->
            <br>
            <%= submit_tag "Save & Submit", :class => "btn btn-primary" %>
            <%= link_to 'Back', campaign_index_path, :class => "btn btn-primary" %>


          </div>

        </div>


<% end %>
</div>

app/views/campaign/show.html.erb
<div class="coat">
  <!--<h1>Brain Cancer</h1>-->
  <H2><strong>HELPER CROWDFUNDING SITE</strong></H2>
</div>
<p></p>
<div class="row">
  <div class="col-md-1">

  </div>
  <div class="track_holder col-md-10">
    <div class="left_tracker col-md-7">

     <p><h2 style="color: black">
        <strong>Illness:</strong>
       <%= @campaign.title %></h2>
      </p>

      <%= image_tag @campaign.image_url(:fully).to_s %>

      <p>
        <strong>Category:</strong>
        <%= @campaign.category %>
      </p>

      <p>
        <strong>Share your Story:</strong><br>
        <%= @campaign.story %>
      </p>

      <p>
        <%= link_to 'Edit', edit_campaign_path(@campaign), :class => "btn btn-primary" %> |
        <%= link_to 'Back', campaign_index_path, :class => "btn btn-primary" %>|
        <%= link_to 'Destroy', campaign_path(@campaign), :class => "btn btn-primary", :confirm => 'ARe you sure?', :method => :delete %>
      </p>
      <!--<%= link_to "Contributions", contributions_path %>-->

      <div class="jumia col-xs-7 ">
      <h2 style="font-style: oblique; color: dimgray">
        Supportive Comments
      </h2>

      <% @campaign.comments.each do |comment| %>
           Name:
          <%= comment.name %><br>
          Comment:
          <%= comment.text %><br>
          <p></p>
      <% end %>
      </div>


      <div style="float: left">
      <%= render 'comments/form' %>
      </div>

    </div>

    <div class="right_tracker col-md-4">
      <p>
        <strong><h3>From the Helper Team</h3></strong><br>
        Help Mr Joe raise funds for His Brain cancer Treatment. He is loving family dad with 3 kids who
        would love to spend more time with their father.
      </p>
      <p>
        <strong>Country:</strong>
        <%= @campaign.country %>
      </p>

      <p>
        <strong>Target amount:</strong>
        <%= @campaign.target_amount %>
      </p>

      <p>
        <strong>Region:</strong>
        <%= @campaign.region %>
      </p>

      <p>
        <strong>City:</strong>
        <%= @campaign.city %>
      </p>

      <div class="donate"><%= link_to "Donate", new_campaign_contribution_path(@campaign) %></div>
      <br>
      <br>
      <h4>Please Share</h4>
      <h6>
        It takes only a few seconds to share this story with the world, please share.
      </h6>
      <br>
      <a href="#" class="btn btn-primary btn-large" onclick="window.open('http://www.facebook.com/sharer.php?u=<?php the_permalink();?>&t=<?php the_title(); ?>',
              'Share on Facebook', 'width=600, height=350'); return false;"><i class="icon-white icon-facebook"></i>
        Share on Facebook</a>      <h4>
      </h4>
      <h4>
        Recent Donations
      </h4>
      <% @campaign.contributions.each do |contribution| %>
         Ghc <%= contribution.donation_amount %><br>
          <%= contribution.first_name %> <%= contribution.last_name %><br>
          <%= contribution.comment %><br>
          <p></p>
      <% end %>
    </div>

  </div>
  <div class="col-md-1">

  </div>

</div>
<%= link_to 'Logout', destroy_user_session_path, :method => :delete %>

app/views/comments/_form.html.erb
<%= form_for([@campaign, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="luxury col-xs-10">
    <div class="form-group">
      <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
    <div class="form-group">
      <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
    <div class="form-group">
      <!--<%= f.label :campaign_id %><br>-->
    <%= f.hidden_field :campaign_id %>
  </div>
  <div class="actions">
    <%= f.submit%>
  </div>
    </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Text</th>
      <th>Campaign</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.text %></td>
        <td><%= comment.campaign %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Text:</strong>
  <%= @comment.text %>
</p>

<p>
  <strong>Campaign:</strong>
  <%= @comment.campaign %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/contributions/_form.html.erb
<div class="boy">
  <%= form_for(@contribution) do |f| %>
      <% if @contribution.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@contribution.errors.count, "error") %> prohibited this contribution from being saved:</h2>

            <ul>
              <% @contribution.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group">
        <%= f.label :first_name %><br>
        <%= f.text_field :first_name,  autofocus: true, class: "form-control", placeholder:"First Name"  %>
      </div>
      <div class="form-group">
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name,  autofocus: true, class: "form-control", placeholder:"Last Name"  %>
      </div>
      <div class="form-group">
        <%= f.label :email %><br>
        <%= f.text_field :email,  autofocus: true, class: "form-control", placeholder:"Email"  %>
      </div>
      <div class="form-group">
        <%= f.label :comment %><br>
        <%= f.text_area :comment, autofocus: true, class: "form-control", placeholder:"Leave a comment"  %>
      </div>
      <div class="form-group">
        <%= f.label :donation_amount %><br>
        <%= f.number_field :donation_amount,  autofocus: true, class: "form-control", placeholder:"Ghc"  %>
      </div>
      <div class="form-group">
        <!--<%= f.label :campaign_id %>--><br>
        <%= f.hidden_field :campaign_id,  autofocus: true, class: "form-control", placeholder:"Campaign_id"  %>
      </div>
      <div class="form-group">
        <%= f.submit "Donate", class:"btn btn-lg btn-primary btn-block" %>
      </div>
  <% end %>
</div>

app/views/contributions/edit.html.erb
<h1>Editing contribution</h1>


<%= render 'form' %>

<%= link_to 'Show', @contribution %> |
<%= link_to 'Back', contributions_path %>

app/views/contributions/index.html.erb
<h1>Listing Contributions</h1>

<table class="rwd-table">
  <tr>
    <th>First name</th>
    <th>Lastname</th>
    <th>Email</th>
    <th>Comment</th>
    <th>Donation amount</th>
    <th>Campaign</th>
  </tr>
  </thead>

  <tbody>
  <% @contributions.each do |contribution| %>
      <tr>
        <td><%= contribution.first_name %></td>
        <td><%= contribution.last_name %></td>
        <td><%= contribution.email %></td>
        <td><%= contribution.comment %></td>
        <td><%= contribution.donation_amount %></td>
        <td><%= contribution.campaign_id %></td>
        <td><%= link_to 'Show', contribution %></td>
        <td><%= link_to 'Edit', edit_contribution_path(contribution) %></td>
        <td><%= link_to 'Destroy', contribution, :id => contribution.id, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contribution', new_contribution_path, class:"btn btn-primary" %>

app/views/contributions/new.html.erb
<h1 style="color: #000000"><bold>New Contribution</bold></h1>

<%= render 'form' %>

<%= link_to 'Back', contributions_path %>

app/views/contributions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @contribution.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contribution.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contribution.email %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @contribution.comment %>
</p>

<p>
  <strong>Donation amount:</strong>
  <%= @contribution.donation_amount %>
</p>

<p>
  <strong>Campaign:</strong>
  <%= @contribution.campaign_id %>
</p>

<%= link_to 'Edit', edit_contribution_path(@contribution) %> |
<%= link_to 'Back', contributions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Helper" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>
</head>
<body class="main">

<p class="navbar-text pull-right">
  <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      
      <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
    <div class="col-lg-3">
      <!--<div class="well sidebar-nav">-->
      <!--<h3>Sidebar</h3>-->
      <!--<ul class="nav nav-list">-->
      <!--<li class="nav-header">Sidebar</li>-->
      <!--<li><%= link_to "Link1", "/path1"  %></li>-->
      <!--<li><%= link_to "Link2", "/path2"  %></li>-->
      <!--<li><%= link_to "Link3", "/path3"  %></li>-->
      <!--</ul>-->
      <!--</div>&lt;!&ndash;/.well &ndash;&gt;-->
    </div><!--/span-->
  </div><!--/row-->

  <footer>
    <p>&copy; Company 2014</p>
  </footer>

</div> <!-- /container -->

</body>
</html>

app/views/layouts/campaign.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Helper" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>
</head>
<body id="image">

<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <a class="navbar-brand" href="#"></a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Add Campaign", new_campaign_path %></li>
        <li><%= link_to "Help Someone", campaign_index_path  %></li>
        <li><%= link_to "Our Story", "/path3"  %></li>
        <li style="text-indent: 430px"><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right" style="padding-top: 14px;">
        <li>Logged in as: <strong><%= current_user.email %></strong></li>

      </ul>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <!--<%= bootstrap_flash %>-->
      <%= yield %>
    </div>
    <div class="col-lg-3">
      <!--<div class="well sidebar-nav">-->
      <!--<h3>Sidebar</h3>-->
      <!--<ul class="nav nav-list">-->
      <!--<li class="nav-header">Sidebar</li>-->
      <!--<li><%= link_to "Link1", "/path1"  %></li>-->
      <!--<li><%= link_to "Link2", "/path2"  %></li>-->
      <!--<li><%= link_to "Link3", "/path3"  %></li>-->
      <!--</ul>-->
      <!--</div>&lt;!&ndash;/.well &ndash;&gt;-->
    </div><!--/span-->
  </div><!--/row-->

  <footer>
    <p>&copy; Company 2014</p>
  </footer>

</div> <!-- /container -->

</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html id="pics">
<head>
  <%= stylesheet_link_tag "application.css" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body id="banku">

<header id="header">
<div id="navbar-collapse" class="navbar-collapse collapse">
  <%= image_tag("logo.png", :size => "260x100") %>
  <ul class="nav navbar-nav navbar-right">
    <li class="nav-item"><%= link_to "Login", new_user_session_path, :class => "btn btn-primary" %></li>
    <li class="nav-item nav-item-cta last"><%= link_to 'Donate to Someone Now!', campaign_index_path, :class => "btn btn-primary" %></a></li>
  </ul><!--//nav-->
</div><!--//navabr-collapse-->
</header>

<%= yield %>

</body>

</html>

app/views/welcome/index.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 panel panel-default panel-wel">
  <p class="margin-base-vertical"><h1>Helper is a Crowdfunding site where<br />you can help anyone pay their Medical Bills.</h1></p>
   <p class="text-center"><h2>Here, your 1ghc can save a persons Life.<br /> You can choose anyone you want to help and donate to.</h2></p>
  <p><%= link_to 'Donate to Someone Now!', campaign_index_path, :class => "btn btn-primary" %></a></p>
</div>
</div>
</div><!--//container-->